### ISSUE TITLE
build for osx-arm64?

### ISSUE THREAD

**Issue by MarkWieczorek** [conda-forge/pypandoc-feedstock#16]
### Comment:

Would it be possible to build a conda package of pypandoc for the new macos M1 chips (osx-arm64)? I am trying to install a large conda package with lots of dependencies, and it turns out that pypandoc is the only one that doesn't work on apple silicon. Thanks!

**Comment by ocefpaf** [comment]
Yes. All you need to do is to send a PR to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt adding the package to the list and the automated infrastructure should take care of the rest.

**Comment by MarkWieczorek** [comment]
Thanks. I put in the request, so hopefully the PR shows up here soon.

**Comment by MarkWieczorek** [comment]
For info, it doesn't seem possible to migrate pypandoc to osx-arm64: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2688

I'm not exactly sure what the problem is, but I will open an issue at the pypandoc repo.

**Comment by ocefpaf** [comment]
Probably the pandoc dependency. I'm not sure we have it for osx-arm64.

**Comment by ocefpaf** [comment]
The osx-arm64 binaries for pandochave been available for sometime. Closing this one.
