### ISSUE TITLE
Pypandoc is not available for Linux and Python 3.6

### ISSUE THREAD

**Issue by bryanwweber** [conda-forge/pypandoc-feedstock#6]
Hi,

Not sure if this is just a CI failure, but the package isn't available for Python 3.6. Is it possible to kick off the CI again?

Thanks!

**Comment by janschulz** [comment]
This should be fixed by the new version (conda forge currently doesn't automatically add a new python version but you need to rerender the feedstock to enable the new version. That has happened with the new upstream version)
